### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by hengchengfei** [MerrickSapsford/MSSTabbedPageViewController#64]
cocoapods version: 1.0.1
xcode7.3

<img width="1749" alt="2016-06-21 15 33 10" src="https://cloud.githubusercontent.com/assets/3182964/16221494/aa35f91e-37c5-11e6-8939-ce9de0e83e4c.png">

**Comment by hengchengfei** [comment]
can‘t use in extension

**Comment by MerrickSapsford** [comment]
Hi,

This has now been fixed in [0.3.2,](https://github.com/MerrickSapsford/MSSTabbedPageViewController/releases/tag/0.3.2) which is available now. 

The `UINavigationBar` components are unavailable when using `MSSTabbedPageViewController` within an App Extension.

Instructions for how to integrate `MSSTabbedPageViewController` correctly in an extension are available in the [wiki here](https://github.com/MerrickSapsford/MSSTabbedPageViewController/wiki/App-Extensions). The `MSS_APP_EXTENSIONS` preprocessor macro is required so that unavailable components are not compiled.
